version: "3.8"
services:
  server:
    build: ./server
    ports:
      - 8000:8000
    environment:
      QUEUE_HOST: queue
      DB_HOST: db
    depends_on:
      - queue
      - db
      - worker
    command: ["./wait-for-it.sh", "queue:5672", "--", "php", "-S", "0.0.0.0:8000"]

  worker:
    build: ./worker
    env_file:
      - ./worker/worker.env
    environment:
      QUEUE_HOST: queue
      DB_HOST: db
    depends_on:
      - queue
      - db
    command: ["./wait-for-it.sh", "queue:5672", "--", "php", "index.php"]

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  queue:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672